variables:
  projectFolder: 'front-end'
  buildOutputFolder: 'front-end/build'
pool:
  name: Hosted Ubuntu 1604
  demands: npm

steps:

- script: |
    pushd $(projectFolder) && npm install && popd
    pushd $(projectFolder) && npm run build && popd
    
## Copy client files to staging directory
- task: CopyFiles@1
  inputs:
    sourceFolder: '$(buildOutputFolder)'
    contents: '**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(Build.ArtifactStagingDirectory)
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build-$(Build.BuildId).zip'
    includeRootFolder: false

## Publish zip file to Azure
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/build-$(Build.BuildId).zip'
