pool:
  vmImage: 'Ubuntu-16.04'
steps:

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'front-end'

- task: Npm@1
  displayName: "Npm Build"
  inputs:
    command: 'custom'
    workingDir: 'front-end'
    customCommand: 'run build'

- task: ArchiveFiles@2
  displayName: 'Archive Files'
  inputs:
    rootFolderOrFile: 'front-end/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/front-end-build-$(Build.BuildId).zip'
    replaceExistingArchive: true

## Publish zip file to Azure
- task: PublishBuildArtifacts@1
  displayName: 'Publish build Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/build-$(Build.BuildId).zip'
